[tool.poetry]
name = "scraping"
version = "0.1.0"
description = ""
authors = ["arthurlemon <coucou@example.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
selenium = "^4.26.1"
beautifulsoup4 = "^4.12.3"
webdriver-manager = "^4.0.2"
selectolax = "^0.3.26"
pydantic = "^2.10.3"
playwright = "^1.49.0"
sqlmodel = "^0.0.22"


[tool.poetry.group.notebook.dependencies]
jupyterlab = "^4.3.1"
jupytext = "^1.16.4"


[tool.poetry.group.dev.dependencies]
ruff = "^0.8.0"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
